name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build with Maven
        run: ./mvnw -B clean install -Pnative
      - name: Save wall-service binary
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main'
        with:
          name: wall-service
          path: wall-service/target/wall-service-*-runner
          retention-days: 3